-- Documentation pointer only — do not execute this file as a migration.
--
-- The old hand-written twelve-table schema diverged from the deployed
-- Supabase project and contained unsafe example policies. The executable,
-- ordered and reproducible source of truth now lives in:
--
--   supabase/migrations/
--
-- Start with 20260827130000_live_schema_snapshot.sql for a clean database,
-- then apply every later migration in lexical order. See
-- docs/SUPABASE_ARCHITECTURE.md for the contract and verification procedure.
-- The local stack is configured by supabase/config.toml and the executable
-- integrity check is `npm run db:verify`.
